language: php

php:
  - 5.3.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev

script:
  - ./vendor/bin/phpunit --configuration phpunit.xml tests/
  - ./var-dump-check src
